# Generated by Django 5.2.14 on 2026-06-03 01:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True, verbose_name="单例键"
                    ),
                ),
                (
                    "admin_session_timeout_minutes",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="管理员登录后台后，超过该时间无操作需重新登录。",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="后台会话超时(分钟)",
                    ),
                ),
                (
                    "webhook_delivery_breaker_threshold",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="连续失败达到该次数后，自动关闭项目 Webhook 投递。",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Webhook 熔断阈值",
                    ),
                ),
                (
                    "webhook_delivery_max_retries",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="单个 Webhook 事件最多自动重试的次数。",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Webhook 最大重试次数",
                    ),
                ),
                (
                    "webhook_delivery_max_backoff_seconds",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Webhook 自动重试的指数退避上限秒数。",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Webhook 最大退避秒数",
                    ),
                ),
                (
                    "webhook_event_timeout_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="待投递 Webhook 事件超过该时间仍未送达时，进入异常巡检。",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Webhook 堆积超时(分钟)",
                    ),
                ),
                (
                    "vault_slot_collect_delay_minutes",
                    models.PositiveIntegerField(
                        default=360,
                        help_text="ERC20 到账确认后等待该时间再聚合归集，期间同槽位同币种不重复创建归集计划。",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="VaultSlot 归集延迟(分钟)",
                    ),
                ),
                (
                    "aml_screening_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="开启后对高于 AML 查询阈值的账单和充币查询外部地址风险。",
                        verbose_name="开启 AML 筛查",
                    ),
                ),
                (
                    "aml_screening_threshold_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        help_text="账单或充币价值大于该阈值时执行 AML 查询。",
                        max_digits=16,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="AML 查询阈值(USD)",
                    ),
                ),
                (
                    "aml_screening_cache_seconds",
                    models.PositiveIntegerField(
                        default=3600,
                        help_text="同一地址 AML 查询成功后在 Django 缓存中保留的秒数。",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="AML 查询缓存秒数",
                    ),
                ),
                (
                    "aml_screening_force_refresh_threshold_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("10000"),
                        help_text="本次业务价值大于该阈值时跳过缓存直接查询。",
                        max_digits=16,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="AML 查询强制刷新阈值(USD)",
                    ),
                ),
                (
                    "quicknode_misttrack_endpoint_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="QuickNode MistTrack add-on 的 JSON-RPC endpoint URL。",
                        verbose_name="QuickNode MistTrack Endpoint",
                    ),
                ),
                (
                    "misttrack_openapi_api_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MistTrack 官方 OpenAPI API Key；配置后优先使用 MistTrack V3 风险评分接口。",
                        max_length=255,
                        verbose_name="MistTrack OpenAPI API Key",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统运行参数",
                "verbose_name_plural": "系统运行参数",
            },
        ),
        migrations.CreateModel(
            name="SystemWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True, verbose_name="单例键"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统热钱包",
                "verbose_name_plural": "系统热钱包",
            },
        ),
    ]
