# Generated by Django 5.2.14 on 2026-07-29 08:19

from django.db import migrations, models
from django_migration_linter.operations import IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_evm_vault_slot_collect_delay_default"),
    ]

    # 新增列自带常量 default=900，PostgreSQL 11+ 下是纯元数据操作，存量单例行由
    # default 直接补齐，不存在 NOT NULL 违约风险。linter 只看到「新增 NOT NULL 列」
    # 这一形态、看不到 default 语义，故在此定点豁免。
    operations = [
        IgnoreMigration(),
        migrations.AddField(
            model_name="systemsettings",
            name="crypto_price_max_age_seconds",
            field=models.PositiveIntegerField(
                default=900,
                help_text="价格距上次成功刷新超过该时长即视为失效，该币暂时退出按法币计价的支付，避免行情源中断期间继续按过期汇率收款。0 表示不校验（行情源长期不可用时应急用）。",
                verbose_name="行情价格最长可用时长(秒)",
            ),
        ),
    ]
