# Generated by Django 5.2.14 on 2026-06-03 01:23

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nonce",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        help_text="唯一。由于存在多次重试机制，此nonce用于幂等去重。",
                        length=22,
                        max_length=22,
                        prefix="",
                        unique=True,
                    ),
                ),
                ("payload", models.JSONField(verbose_name="内容")),
                (
                    "delivery_url",
                    models.URLField(blank=True, default="", verbose_name="投递地址"),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("post_json", "POST JSON"),
                            ("get_query", "GET Query"),
                        ],
                        default="post_json",
                        max_length=16,
                        verbose_name="投递方式",
                    ),
                ),
                (
                    "expected_response_body",
                    models.CharField(
                        default="ok", max_length=32, verbose_name="成功响应内容"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待投递"),
                            ("succeeded", "已送达"),
                            ("failed", "投递失败"),
                        ],
                        default="pending",
                        verbose_name="状态",
                    ),
                ),
                (
                    "schedule_locked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次投递"
                    ),
                ),
                (
                    "delivery_locked_until",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="投递锁定至"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, default="", verbose_name="投递报错信息"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="送达时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "事件",
                "verbose_name_plural": "事件",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("try_number", models.PositiveSmallIntegerField(verbose_name="次数")),
                ("request_headers", models.JSONField()),
                ("request_body", models.TextField()),
                ("response_status", models.PositiveIntegerField(null=True)),
                ("response_headers", models.JSONField(null=True)),
                ("response_body", models.TextField(blank=True, default="")),
                ("duration_ms", models.PositiveIntegerField(verbose_name="耗时(ms)")),
                ("ok", models.BooleanField(default=False, verbose_name="成功")),
                (
                    "error",
                    models.TextField(
                        blank=True, default="", editable=False, verbose_name="错误"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="webhooks.webhookevent",
                        verbose_name="事件",
                    ),
                ),
            ],
            options={
                "verbose_name": "投递日志",
                "verbose_name_plural": "投递日志",
                "ordering": ("-created_at",),
            },
        ),
    ]
