# Generated by Django 5.2.14 on 2026-06-03 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fiat",
            fields=[
                (
                    "code",
                    models.CharField(
                        primary_key=True, serialize=False, verbose_name="代码"
                    ),
                ),
            ],
            options={
                "verbose_name": "法币",
                "verbose_name_plural": "法币",
            },
        ),
        migrations.CreateModel(
            name="ChainCryptoDeployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, db_index=True, default="", verbose_name="合约地址"
                    ),
                ),
                ("decimals", models.PositiveSmallIntegerField(verbose_name="精度")),
                ("active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chain_crypto_deployments",
                        to="chains.chain",
                        verbose_name="链",
                    ),
                ),
            ],
            options={
                "verbose_name": "链上币种部署",
                "verbose_name_plural": "链上币种部署",
            },
        ),
        migrations.CreateModel(
            name="Crypto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True, verbose_name="名称")),
                (
                    "symbol",
                    models.CharField(
                        help_text="例如:ETH、USDT", unique=True, verbose_name="代码"
                    ),
                ),
                (
                    "prices",
                    models.JSONField(blank=True, default=dict, verbose_name="价格"),
                ),
                (
                    "coingecko_id",
                    models.CharField(
                        blank=True, null=True, unique=True, verbose_name="CoinGecko ID"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "is_native",
                    models.BooleanField(default=False, verbose_name="原生币"),
                ),
                (
                    "chains",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cryptos",
                        through="currencies.ChainCryptoDeployment",
                        to="chains.chain",
                        verbose_name="支持的链",
                    ),
                ),
            ],
            options={
                "verbose_name": "加密货币",
                "verbose_name_plural": "加密货币",
            },
        ),
        migrations.AddField(
            model_name="chaincryptodeployment",
            name="crypto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chain_crypto_deployments",
                to="currencies.crypto",
                verbose_name="加密货币",
            ),
        ),
        migrations.AddConstraint(
            model_name="chaincryptodeployment",
            constraint=models.UniqueConstraint(
                fields=("crypto", "chain"),
                name="uniq_chain_crypto_deployment_crypto_chain",
            ),
        ),
        migrations.AddConstraint(
            model_name="chaincryptodeployment",
            constraint=models.UniqueConstraint(
                fields=("chain", "address"),
                name="uniq_chain_crypto_deployment_chain_address",
            ),
        ),
    ]
