# Generated by Django 5.2.14 on 2026-07-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0002_fix_pol_coingecko_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="crypto",
            name="prices_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="最近一次成功写入行情的时间。价格陈旧时该币会退出支付计价，避免行情源中断期间继续按过期汇率收款。",
                null=True,
                verbose_name="价格更新时间",
            ),
        ),
    ]
