# Generated by Django 5.2.14 on 2026-06-03 01:23

import common.fields
import django.db.models.deletion
import shortuuid.django_fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="23456789ABCDEFGHJKLMNPQRSTUVWXYZ",
                        db_index=True,
                        editable=False,
                        length=8,
                        max_length=11,
                        prefix="XC-",
                        unique=True,
                        verbose_name="Appid",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="对外作为商户名展示",
                        unique=True,
                        verbose_name="项目名称",
                    ),
                ),
                (
                    "ip_white_list",
                    models.TextField(
                        default="*",
                        help_text="只有符合白名单的 IP 才可以与本网关交互，支持 IP 地址或 IP 网段<br>可同时设置多个，中间用英文逗号 ',' 分割<br>* 代表允许所有 IP 访问",
                        verbose_name="IP白名单",
                    ),
                ),
                (
                    "webhook",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="用于本网关发送通知到商户后端",
                        verbose_name="通知地址",
                    ),
                ),
                (
                    "webhook_open",
                    models.BooleanField(default=True, verbose_name="通知状态"),
                ),
                (
                    "failed_count",
                    models.PositiveIntegerField(default=0, verbose_name="连续失败次数"),
                ),
                (
                    "pre_notify",
                    models.BooleanField(
                        default=False,
                        help_text="刚出块(尚未达到区块确认数)，就发送一次预通知",
                        verbose_name="开启预通知",
                    ),
                ),
                (
                    "fast_confirm_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10"),
                        help_text="低于该金额的账单无需等待区块确认数，立即确认",
                        max_digits=10,
                        verbose_name="快速确认阈值（USD）",
                    ),
                ),
                (
                    "hmac_key",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=32,
                        max_length=32,
                        prefix="",
                        verbose_name="HMAC密钥",
                    ),
                ),
                (
                    "vault",
                    common.fields.AddressField(
                        blank=True,
                        db_index=True,
                        help_text="用于生成 EVM VaultSlot 合约的不可变 vault。留空时禁止生成 VaultSlot；一旦设置不可修改。",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="收款归集地址",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, verbose_name="客户UID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("uid", "project"), name="uniq_customer_uid_project"
                    )
                ],
            },
        ),
    ]
