# Generated by Django 5.2.14 on 2026-06-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("quicknode_misttrack", "QuickNode MistTrack"),
                            ("misttrack_openapi", "MistTrack OpenAPI"),
                        ],
                        db_index=True,
                        default="quicknode_misttrack",
                        max_length=32,
                        verbose_name="数据来源",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "查询成功"), ("failed", "查询失败")],
                        db_index=True,
                        max_length=16,
                        verbose_name="查询状态",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("invoice", "账单"), ("deposit", "充币")],
                        db_index=True,
                        max_length=16,
                        verbose_name="目标类型",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="查询地址"
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="交易哈希"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Low", "Low"),
                            ("Moderate", "Moderate"),
                            ("High", "High"),
                            ("Severe", "Severe"),
                        ],
                        db_index=True,
                        max_length=16,
                        null=True,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="风险分数",
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="原始响应摘要"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误摘要"),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="查询完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "AML 评估",
                "verbose_name_plural": "AML 评估",
                "ordering": ("-created_at",),
            },
        ),
    ]
