# Generated by Django 5.2.14 on 2026-06-03 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aml", "0001_initial"),
        ("deposits", "0001_initial"),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskassessment",
            name="deposit",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aml_assessment",
                to="deposits.deposit",
                verbose_name="充币",
            ),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aml_assessment",
                to="invoices.invoice",
                verbose_name="账单",
            ),
        ),
        migrations.AddConstraint(
            model_name="riskassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("invoice__isnull", False), ("deposit__isnull", True)),
                    models.Q(("invoice__isnull", True), ("deposit__isnull", False)),
                    _connector="OR",
                ),
                name="aml_assessment_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="riskassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("target_type", "invoice"),
                        ("invoice__isnull", False),
                        ("deposit__isnull", True),
                    ),
                    models.Q(
                        ("target_type", "deposit"),
                        ("invoice__isnull", True),
                        ("deposit__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="aml_assessment_target_type_matches_target",
            ),
        ),
    ]
