# Generated by Django 5.2.14 on 2026-06-03 01:23

import common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TronWatchCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_address",
                    common.fields.AddressField(
                        db_index=True, max_length=100, verbose_name="合约地址"
                    ),
                ),
                (
                    "last_scanned_block",
                    models.PositiveIntegerField(
                        default=0, verbose_name="已扫描到的区块"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "last_error",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="最近错误"
                    ),
                ),
                (
                    "last_error_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近错误时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tron_watch_cursors",
                        to="chains.chain",
                        verbose_name="链",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tron 扫描游标",
                "verbose_name_plural": "Tron 扫描游标",
                "ordering": ("chain_id", "contract_address"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chain", "contract_address"),
                        name="uniq_tron_watch_cursor_chain_contract_address",
                    )
                ],
            },
        ),
    ]
