# Generated by Django 5.2.14 on 2026-06-03 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StressRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="名称")),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="支付模拟次数"),
                ),
                (
                    "deposit_count",
                    models.PositiveIntegerField(default=0, verbose_name="充币模拟次数"),
                ),
                (
                    "deposit_customer_count",
                    models.PositiveIntegerField(default=0, verbose_name="充币客户数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("preparing", "准备中"),
                            ("failed", "准备失败"),
                            ("ready", "就绪"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "succeeded",
                    models.PositiveIntegerField(default=0, verbose_name="成功"),
                ),
                ("failed", models.PositiveIntegerField(default=0, verbose_name="失败")),
                (
                    "skipped",
                    models.PositiveIntegerField(default=0, verbose_name="跳过"),
                ),
                ("error", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.project",
                        verbose_name="专用项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "压力测试",
                "verbose_name_plural": "压力测试",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceStressCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="序号")),
                (
                    "scheduled_offset",
                    models.FloatField(
                        help_text="相对于 Stress.started_at 的偏移秒数",
                        verbose_name="调度偏移(秒)",
                    ),
                ),
                (
                    "invoice_sys_no",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="系统单号"
                    ),
                ),
                (
                    "invoice_out_no",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="商户单号"
                    ),
                ),
                (
                    "crypto",
                    models.CharField(blank=True, max_length=32, verbose_name="币种"),
                ),
                (
                    "chain",
                    models.CharField(blank=True, max_length=32, verbose_name="链"),
                ),
                (
                    "pay_address",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="支付地址"
                    ),
                ),
                (
                    "pay_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        max_digits=36,
                        null=True,
                        verbose_name="支付金额",
                    ),
                ),
                (
                    "payer_address",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="付款地址"
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="交易哈希"
                    ),
                ),
                (
                    "webhook_received",
                    models.BooleanField(default=False, verbose_name="已收到 Webhook"),
                ),
                (
                    "webhook_signature_ok",
                    models.BooleanField(default=False, verbose_name="签名验证"),
                ),
                (
                    "webhook_payload_ok",
                    models.BooleanField(default=False, verbose_name="Payload 验证"),
                ),
                (
                    "webhook_nonce_ok",
                    models.BooleanField(default=False, verbose_name="Nonce 验证"),
                ),
                (
                    "webhook_timestamp_ok",
                    models.BooleanField(default=False, verbose_name="时间戳验证"),
                ),
                (
                    "webhook_received_nonces",
                    models.JSONField(
                        blank=True, default=list, verbose_name="已收到的 Nonce 列表"
                    ),
                ),
                (
                    "billing_mode",
                    models.CharField(
                        choices=[("differ", "差额"), ("contract", "合约")],
                        default="differ",
                        max_length=16,
                        verbose_name="计费模式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待执行"),
                            ("creating", "创建账单中"),
                            ("created", "账单已创建"),
                            ("paying", "支付中"),
                            ("paid", "链上已广播"),
                            ("webhook_ok", "Webhook 验证通过"),
                            ("succeeded", "成功"),
                            ("failed", "失败"),
                            ("skipped", "跳过"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "collection_verified",
                    models.BooleanField(default=False, verbose_name="归集已验证"),
                ),
                (
                    "collection_hash",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="归集交易哈希"
                    ),
                ),
                (
                    "collection_done_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="归集完成时间"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "invoice_created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="账单创建完成时间"
                    ),
                ),
                (
                    "api_done_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="选支付方式完成时间"
                    ),
                ),
                (
                    "chain_paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="链上广播完成时间"
                    ),
                ),
                (
                    "webhook_received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Webhook 处理完成时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "stress_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="stress.stressrun",
                        verbose_name="测试轮次",
                    ),
                ),
            ],
            options={
                "verbose_name": "账单测试",
                "verbose_name_plural": "账单测试",
                "ordering": ["stress_run", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="DepositStressCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="序号")),
                (
                    "scheduled_offset",
                    models.FloatField(
                        help_text="相对于 Stress.started_at 的偏移秒数",
                        verbose_name="调度偏移(秒)",
                    ),
                ),
                (
                    "customer_uid",
                    models.CharField(max_length=128, verbose_name="客户 UID"),
                ),
                ("crypto", models.CharField(max_length=32, verbose_name="币种")),
                ("chain", models.CharField(max_length=32, verbose_name="链")),
                (
                    "deposit_address",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="充值地址"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=18, max_digits=36, verbose_name="充值金额"
                    ),
                ),
                (
                    "payer_address",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="付款地址"
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="交易哈希"
                    ),
                ),
                (
                    "webhook_received",
                    models.BooleanField(default=False, verbose_name="已收到 Webhook"),
                ),
                (
                    "webhook_signature_ok",
                    models.BooleanField(default=False, verbose_name="签名验证"),
                ),
                (
                    "webhook_payload_ok",
                    models.BooleanField(default=False, verbose_name="Payload 验证"),
                ),
                (
                    "webhook_nonce_ok",
                    models.BooleanField(default=False, verbose_name="Nonce 验证"),
                ),
                (
                    "webhook_timestamp_ok",
                    models.BooleanField(default=False, verbose_name="时间戳验证"),
                ),
                (
                    "webhook_received_nonces",
                    models.JSONField(
                        blank=True, default=list, verbose_name="已收到的 Nonce 列表"
                    ),
                ),
                (
                    "collection_verified",
                    models.BooleanField(default=False, verbose_name="归集已验证"),
                ),
                (
                    "collection_hash",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="归集交易哈希"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待执行"),
                            ("creating", "获取充值地址中"),
                            ("paying", "模拟充值中"),
                            ("paid", "已充值"),
                            ("webhook_ok", "Webhook 验证通过"),
                            ("succeeded", "成功"),
                            ("failed", "失败"),
                            ("skipped", "跳过"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "api_done_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="获取充值地址完成时间"
                    ),
                ),
                (
                    "chain_paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="链上充值完成时间"
                    ),
                ),
                (
                    "webhook_received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Webhook 处理完成时间"
                    ),
                ),
                (
                    "collection_done_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="归集完成时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "stress_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposit_cases",
                        to="stress.stressrun",
                        verbose_name="测试轮次",
                    ),
                ),
            ],
            options={
                "verbose_name": "充币测试",
                "verbose_name_plural": "充币测试",
                "ordering": ["stress_run", "sequence"],
            },
        ),
    ]
