# Generated by Django 5.2.12 on 2026-05-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stress", "0002_depositstresscase_api_done_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicestresscase",
            name="billing_mode",
            field=models.CharField(
                choices=[("differ", "差额"), ("contract", "合约")],
                default="differ",
                max_length=16,
                verbose_name="计费模式",
            ),
        ),
        migrations.AddField(
            model_name="invoicestresscase",
            name="collection_done_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="归集完成时间"
            ),
        ),
        migrations.AddField(
            model_name="invoicestresscase",
            name="collection_hash",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="归集交易哈希"
            ),
        ),
        migrations.AddField(
            model_name="invoicestresscase",
            name="collection_verified",
            field=models.BooleanField(default=False, verbose_name="归集已验证"),
        ),
    ]
