# Generated by Django 5.2.14 on 2026-06-03 01:23

import common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sys_no",
                    common.fields.SysNoField(
                        alphabet=None,
                        db_index=True,
                        editable=False,
                        length=8,
                        max_length=32,
                        prefix="DXC",
                        unique=True,
                        verbose_name="系统单号",
                    ),
                ),
                (
                    "worth",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=16,
                        verbose_name="价值(USD)",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Low", "Low"),
                            ("Moderate", "Moderate"),
                            ("High", "High"),
                            ("Severe", "Severe"),
                        ],
                        db_index=True,
                        max_length=16,
                        null=True,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="风险分数",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "transfer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chains.transfer",
                        verbose_name="链上转账",
                    ),
                ),
            ],
            options={
                "verbose_name": "充币",
                "verbose_name_plural": "充币",
            },
        ),
    ]
