# Generated by Django 5.2.14 on 2026-06-16 05:55

import common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    common.fields.AddressField(
                        db_index=True, max_length=100, unique=True, verbose_name="地址"
                    ),
                ),
                (
                    "chain_type",
                    models.CharField(
                        choices=[("evm", "EVM"), ("tron", "Tron")],
                        verbose_name="链类型",
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[("hot_wallet", "热钱包")], verbose_name="用途"
                    ),
                ),
                (
                    "bip44_account",
                    models.PositiveIntegerField(verbose_name="BIP44 账户层级"),
                ),
                (
                    "address_index",
                    models.PositiveIntegerField(default=0, verbose_name="地址索引"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "地址",
                "verbose_name_plural": "地址",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TxHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash",
                    common.fields.HashField(
                        db_index=True,
                        max_length=100,
                        unique=False,
                        verbose_name="交易哈希",
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="版本")),
                (
                    "expires_at_ms",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="过期时间(ms)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "交易哈希历史",
                "verbose_name_plural": "交易哈希历史",
                "ordering": ("tx_task_id", "version"),
            },
        ),
        migrations.CreateModel(
            name="TxTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tx_type",
                    models.CharField(
                        choices=[
                            ("vault_slot_deploy", "🏦 VaultSlot 部署"),
                            ("vault_slot_collect", "💰 VaultSlot 归集"),
                        ],
                        verbose_name="类型",
                    ),
                ),
                (
                    "tx_hash",
                    common.fields.HashField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=False,
                        verbose_name="交易哈希",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "待提交"),
                            ("submitted", "已提交"),
                            ("succeeded", "成功"),
                            ("failed", "失败"),
                        ],
                        default="queued",
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "链上任务",
                "verbose_name_plural": "链上任务",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="VaultSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[("deposit", "充值收款"), ("invoice", "账单收款")],
                        db_index=True,
                        max_length=16,
                        verbose_name="用途",
                    ),
                ),
                (
                    "invoice_index",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="账单槽位序号"
                    ),
                ),
                (
                    "address",
                    common.fields.AddressField(
                        db_index=True, max_length=100, verbose_name="收款地址"
                    ),
                ),
                (
                    "salt",
                    models.BinaryField(max_length=32, verbose_name="CREATE2 Salt"),
                ),
                (
                    "is_deployed",
                    models.BooleanField(
                        default=False,
                        help_text="链上已观测到该 VaultSlot 合约 code。",
                        verbose_name="是否已部署",
                    ),
                ),
                (
                    "has_received",
                    models.BooleanField(default=False, verbose_name="是否收到过资金"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "收款地址",
                "verbose_name_plural": "收款地址",
            },
        ),
        migrations.CreateModel(
            name="VaultSlotBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=80,
                        verbose_name="链上最小单位余额",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=30, default=0, max_digits=80, verbose_name="余额"
                    ),
                ),
                (
                    "worth",
                    models.DecimalField(
                        decimal_places=30,
                        default=0,
                        max_digits=80,
                        verbose_name="价值(USD)",
                    ),
                ),
                (
                    "synced_block_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="同步区块"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="同步时间"
                    ),
                ),
                (
                    "last_tx_hash",
                    common.fields.HashField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=False,
                        verbose_name="最近触发交易",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "收款地址余额",
                "verbose_name_plural": "收款地址余额",
                "ordering": ("vault_slot_id", "crypto_id"),
            },
        ),
        migrations.CreateModel(
            name="VaultSlotCollectSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(db_index=True, verbose_name="计划执行时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "收款地址归集计划",
                "verbose_name_plural": "收款地址归集计划",
                "ordering": ("due_at", "pk"),
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "encrypted_mnemonic",
                    models.TextField(editable=False, verbose_name="加密助记词"),
                ),
            ],
            options={
                "verbose_name": "钱包",
                "verbose_name_plural": "钱包",
            },
        ),
        migrations.CreateModel(
            name="Chain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("ethereum", "Ethereum"),
                            ("bsc", "BSC"),
                            ("polygon", "Polygon"),
                            ("arbitrum-one", "Arbitrum One"),
                            ("optimism", "Optimism"),
                            ("base", "Base"),
                            ("avalanche", "Avalanche C-Chain"),
                            ("linea", "Linea"),
                            ("scroll", "Scroll"),
                            ("tron", "Tron"),
                            ("sepolia", "Sepolia"),
                            ("nile", "Nile"),
                            ("anvil", "Anvil Local"),
                        ],
                        unique=True,
                        verbose_name="代码",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("evm", "EVM"), ("tron", "Tron")],
                        editable=False,
                        help_text="由 code 常量自动决定，不可手动修改。",
                        max_length=16,
                        verbose_name="类型",
                    ),
                ),
                (
                    "is_testnet",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="由 code 常量自动决定，不可手动修改。",
                        verbose_name="测试网",
                    ),
                ),
                (
                    "latest_block_number",
                    models.PositiveIntegerField(default=0, verbose_name="最新区块"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=100, verbose_name="排序序号"),
                ),
                ("active", models.BooleanField(default=False, verbose_name="启用")),
                (
                    "evm_log_max_block_range",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="EVM 扫描器单次 eth_getLogs 请求允许覆盖的最大区块数。",
                        verbose_name="EVM 单次日志请求最大区块数",
                    ),
                ),
                ("rpc", models.CharField(blank=True, default="", verbose_name="RPC")),
                (
                    "tron_api_key",
                    models.CharField(
                        blank=True, default="", verbose_name="Tron API Key"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "last_scanned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="最近扫描时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "链",
                "verbose_name_plural": "链",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("active", False),
                            models.Q(
                                ("type", "evm"), models.Q(("rpc", ""), _negated=True)
                            ),
                            models.Q(
                                ("type", "tron"),
                                models.Q(("tron_api_key", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="chain_active_requires_runtime_config",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block", models.IntegerField(verbose_name="区块高度")),
                (
                    "block_hash",
                    common.fields.HashField(
                        db_index=True,
                        max_length=100,
                        unique=False,
                        verbose_name="区块哈希",
                    ),
                ),
                (
                    "hash",
                    common.fields.HashField(
                        db_index=True, max_length=100, unique=False, verbose_name="哈希"
                    ),
                ),
                (
                    "event_index",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="同一笔链上交易内第几条入账事件；旧数据或手工记录可为空。",
                        null=True,
                        verbose_name="交易内事件序号",
                    ),
                ),
                (
                    "from_address",
                    common.fields.AddressField(
                        db_index=True, max_length=100, verbose_name="发送地址"
                    ),
                ),
                (
                    "to_address",
                    common.fields.AddressField(
                        db_index=True, max_length=100, verbose_name="目的地址"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=0, max_digits=32, verbose_name="数值"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=8, max_digits=32, verbose_name="数量"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("unmatched", "未归类"),
                            ("invoice", "💳 账单收款"),
                            ("deposit", "💰 充值收款"),
                        ],
                        default="unmatched",
                        verbose_name="类型",
                    ),
                ),
                (
                    "confirm_mode",
                    models.CharField(
                        choices=[("full", "完全"), ("quick", "快速")],
                        default="full",
                        help_text="当前仅 Invoice 业务根据 fast_confirm_threshold 动态设置 QUICK/FULL；Deposit 始终使用默认 FULL，走完整区块确认流程。",
                        max_length=8,
                        verbose_name="确认模式",
                    ),
                ),
                (
                    "timestamp",
                    models.PositiveIntegerField(db_index=True, verbose_name="时间戳"),
                ),
                ("datetime", models.DateTimeField(verbose_name="日期")),
                (
                    "status",
                    models.CharField(
                        choices=[("confirming", "确认中"), ("confirmed", "已确认")],
                        default="confirming",
                        verbose_name="状态",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chains.chain",
                        verbose_name="链",
                    ),
                ),
            ],
            options={
                "verbose_name": "转账",
                "verbose_name_plural": "转账",
                "ordering": ("-timestamp",),
            },
        ),
    ]
