# Generated by Django 5.2.14 on 2026-06-03 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0001_initial"),
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="crypto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="currencies.crypto",
                verbose_name="加密货币",
            ),
        ),
        migrations.AddField(
            model_name="txhash",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tx_hashes",
                to="chains.chain",
                verbose_name="链",
            ),
        ),
        migrations.AddField(
            model_name="txtask",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="chains.chain",
                verbose_name="链",
            ),
        ),
        migrations.AddField(
            model_name="txtask",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="chains.address",
                verbose_name="发送地址",
            ),
        ),
        migrations.AddField(
            model_name="txhash",
            name="tx_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tx_hashes",
                to="chains.txtask",
                verbose_name="链上任务",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chains.wallet",
                verbose_name="钱包",
            ),
        ),
        migrations.AddConstraint(
            model_name="addresschainstate",
            constraint=models.UniqueConstraint(
                fields=("address", "chain"),
                name="uniq_address_chain_state_address_chain",
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.UniqueConstraint(
                fields=("chain", "hash"), name="uniq_transfer_chain_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="txtask",
            constraint=models.UniqueConstraint(
                fields=("chain", "tx_hash"), name="uniq_tx_task_chain_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="txhash",
            constraint=models.UniqueConstraint(
                fields=("chain", "hash"), name="uniq_tx_hash_chain_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="txhash",
            constraint=models.UniqueConstraint(
                fields=("tx_task", "version"), name="uniq_tx_hash_task_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                fields=("wallet", "chain_type", "usage", "address_index"),
                name="uniq_address_wallet_chain_usage_addridx",
            ),
        ),
    ]
