MIN_INVOICE_DURATION = 10
MAX_INVOICE_DURATION = 30


LENGTH_OF_EVM_HASH = 66


APPID_HEADER = "XC-Appid"
NONCE_HEADER = "XC-Nonce"
SIGNATURE_HEADER = "XC-Signature"
TIMESTAMP_HEADER = "XC-Timestamp"


UPPER_ALPHABET = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ"
