# Generated by Django 5.2.14 on 2026-06-03 01:23

import common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0001_initial"),
        ("currencies", "0001_initial"),
        ("projects", "0001_initial"),
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DifferRecipientAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, verbose_name="备注名称")),
                (
                    "chain_type",
                    models.CharField(
                        choices=[("evm", "EVM"), ("tron", "Tron")],
                        help_text="EVM: Ethereum, BSC, Polygon, Base...<br>Tron: Tron",
                        verbose_name="地址格式",
                    ),
                ),
                (
                    "address",
                    common.fields.AddressField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="差额账单收款地址",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "差额账单收款地址",
                "verbose_name_plural": "差额账单收款地址",
            },
        ),
        migrations.CreateModel(
            name="EpayMerchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pid",
                    models.PositiveBigIntegerField(
                        unique=True, verbose_name="EPay 商户 ID"
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        help_text="EPay 协议签名密钥。建议使用强随机字符串，不要与项目 HMAC 密钥重用。",
                        max_length=128,
                        verbose_name="EPay 密钥",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epay_merchant",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "EPay 商户",
                "verbose_name_plural": "EPay 商户",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sys_no",
                    common.fields.SysNoField(
                        alphabet=None,
                        db_index=True,
                        editable=False,
                        length=8,
                        max_length=32,
                        prefix="INV",
                        unique=True,
                        verbose_name="系统单号",
                    ),
                ),
                ("out_no", models.CharField(db_index=True, verbose_name="商户单号")),
                ("title", models.CharField(verbose_name="标题")),
                ("currency", models.CharField(verbose_name="计价货币")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=8, max_digits=32, verbose_name="金额"
                    ),
                ),
                (
                    "methods",
                    models.JSONField(default=dict, verbose_name="支持的支付方式"),
                ),
                (
                    "pay_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="支付加密货币数量可能在原始数量上差额浮动",
                        max_digits=32,
                        null=True,
                        verbose_name="支付加密货币数量",
                    ),
                ),
                (
                    "pay_address",
                    common.fields.AddressField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="支付地址",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="支付开始时间"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="支付截止时间")),
                (
                    "notify_url",
                    models.URLField(
                        blank=True, default="", verbose_name="异步通知地址"
                    ),
                ),
                (
                    "return_url",
                    models.URLField(
                        blank=True, default="", verbose_name="支付成功后同步跳转地址"
                    ),
                ),
                (
                    "worth",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=16,
                        verbose_name="价值(USD)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "待支付"),
                            ("confirming", "确认中"),
                            ("completed", "已完成"),
                            ("expired", "已超时"),
                        ],
                        default="waiting",
                        verbose_name="状态",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Low", "Low"),
                            ("Moderate", "Moderate"),
                            ("High", "High"),
                            ("Severe", "Severe"),
                        ],
                        db_index=True,
                        max_length=16,
                        null=True,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="风险分数",
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[("native", "Xcash 原生"), ("epay_v1", "EPay V1")],
                        db_index=True,
                        default="native",
                        max_length=16,
                        verbose_name="协议",
                    ),
                ),
                (
                    "billing_mode",
                    models.CharField(
                        choices=[("differ", "差额"), ("contract", "合约")],
                        db_index=True,
                        default="differ",
                        max_length=16,
                        verbose_name="计费模式",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chains.chain",
                        verbose_name="链",
                    ),
                ),
                (
                    "crypto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="currencies.crypto",
                        verbose_name="加密货币",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "transfer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chains.transfer",
                        verbose_name="链上转账",
                    ),
                ),
            ],
            options={
                "verbose_name": "账单",
                "verbose_name_plural": "账单",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EpayOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.CharField(max_length=32, verbose_name="EPay 商户 ID")),
                (
                    "trade_no",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="EPay 平台订单号"
                    ),
                ),
                (
                    "out_trade_no",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="商户订单号"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="支付类型"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="商品名称")),
                (
                    "money",
                    models.DecimalField(
                        decimal_places=2, max_digits=32, verbose_name="订单金额"
                    ),
                ),
                ("notify_url", models.URLField(verbose_name="异步通知地址")),
                (
                    "return_url",
                    models.URLField(
                        blank=True, default="", verbose_name="同步跳转地址"
                    ),
                ),
                (
                    "param",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="业务扩展参数",
                    ),
                ),
                (
                    "sign_type",
                    models.CharField(
                        default="MD5", max_length=16, verbose_name="签名类型"
                    ),
                ),
                (
                    "raw_request",
                    models.JSONField(default=dict, verbose_name="原始请求"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="invoices.epaymerchant",
                        verbose_name="EPay 商户",
                    ),
                ),
                (
                    "notify_event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="webhooks.webhookevent",
                        verbose_name="通知事件",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epay_order",
                        to="invoices.invoice",
                        verbose_name="账单",
                    ),
                ),
            ],
            options={
                "verbose_name": "EPay 订单",
                "verbose_name_plural": "EPay 订单",
            },
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("project", "out_no"), name="uniq_invoice_project_out_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "waiting")),
                fields=("project", "crypto", "chain", "pay_address", "pay_amount"),
                name="uniq_invoice_active_payment",
            ),
        ),
        migrations.AddConstraint(
            model_name="epayorder",
            constraint=models.UniqueConstraint(
                fields=("merchant", "out_trade_no"),
                name="uniq_epay_order_merchant_out_trade_no",
            ),
        ),
        migrations.AddConstraint(
            model_name="epayorder",
            constraint=models.UniqueConstraint(
                fields=("merchant", "trade_no"),
                name="uniq_epay_order_merchant_trade_no",
            ),
        ),
    ]
