# Generated by Django 5.2.12 on 2026-05-21 11:29

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0011_invoice_risk_level_invoice_risk_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="billing_mode",
            field=models.CharField(
                choices=[("differ", "差额"), ("contract", "合约")],
                db_index=True,
                default="differ",
                max_length=16,
                verbose_name="计费模式",
            ),
        ),
        migrations.AddField(
            model_name="invoicepayslot",
            name="billing_mode",
            field=models.CharField(
                choices=[("differ", "差额"), ("contract", "合约")],
                default="differ",
                max_length=16,
                verbose_name="计费模式",
            ),
        ),
        migrations.AddField(
            model_name="invoicepayslot",
            name="recipient_address",
            field=common.fields.AddressField(
                blank=True,
                db_index=True,
                help_text="仅合约账单填写,差额账单留空。后续部署 collector 时使用此值,保证地址不漂移。",
                max_length=100,
                null=True,
                verbose_name="派生 collector 时使用的归集目标地址",
            ),
        ),
    ]
