# Generated by Django 5.2.12 on 2026-05-24 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignerRequestAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("endpoint", models.CharField(max_length=64)),
                (
                    "wallet_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "chain_type",
                    models.CharField(
                        blank=True, choices=[("evm", "EVM")], default="", max_length=16
                    ),
                ),
                ("bip44_account", models.PositiveIntegerField(blank=True, null=True)),
                ("address_index", models.PositiveIntegerField(blank=True, null=True)),
                ("remote_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("rate_limited", "Rate Limited"),
                        ],
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=16)),
                ("detail", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Signer 请求审计",
                "verbose_name_plural": "Signer 请求审计",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SignerWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xcash_wallet_id", models.BigIntegerField(db_index=True, unique=True)),
                ("encrypted_mnemonic", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("frozen", "Frozen")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Signer 钱包",
                "verbose_name_plural": "Signer 钱包",
                "ordering": ("xcash_wallet_id",),
            },
        ),
        migrations.CreateModel(
            name="SignerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chain_type",
                    models.CharField(
                        choices=[("evm", "EVM")], max_length=16, verbose_name="链类型"
                    ),
                ),
                (
                    "bip44_account",
                    models.PositiveIntegerField(verbose_name="BIP44 账户层级"),
                ),
                ("address_index", models.PositiveIntegerField(verbose_name="地址索引")),
                (
                    "address",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="地址"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="wallets.signerwallet",
                        verbose_name="Signer 钱包",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signer 地址",
                "verbose_name_plural": "Signer 地址",
                "ordering": (
                    "wallet_id",
                    "chain_type",
                    "bip44_account",
                    "address_index",
                ),
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "wallet",
                            "chain_type",
                            "bip44_account",
                            "address_index",
                        ),
                        name="uniq_signer_addr_wallet_chain_bip44acc_addridx",
                    ),
                    models.UniqueConstraint(
                        fields=("chain_type", "address"),
                        name="uniq_signer_addr_chain_address",
                    ),
                ],
            },
        ),
    ]
