# Generated by Django 5.2.12 on 2026-05-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signeraddress",
            name="chain_type",
            field=models.CharField(
                choices=[("evm", "EVM")], max_length=16, verbose_name="链类型"
            ),
        ),
        migrations.AlterField(
            model_name="signerrequestaudit",
            name="chain_type",
            field=models.CharField(
                blank=True, choices=[("evm", "EVM")], default="", max_length=16
            ),
        ),
    ]
